### ISSUE TITLE
好像又出问题了，不能用了

### ISSUE THREAD

**Issue by zangqiourun** [elphen-wang/FreeAI#10]
Traceback (most recent call last):
  File ".\request_llm\bridge_chatgpt.py", line 189, in predict
    if ('data: [DONE]' in chunk_decoded) or (len(json.loads(chunk_decoded[6:])['choices'][0]["delta"]) == 0):
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

还有就是报错：
Please enable cookies.
Sorry, you have been blocked
You are unable to access fakeopen.com
Why have I been blocked?
This website is using a security service to protect itself from online attacks. The action you just performed triggered the security solution. There are several actions that could trigger this block including submitting a certain word or phrase, a SQL command or malformed data.

What can I do to resolve this?
You can email the site owner to let them know you were blocked. Please include what you were doing when this page came up and the Cloudflare Ray ID found at the bottom of this page.

Cloudflare Ray ID: 7fa088e2486adff5 • Your IP: Click to reveal 2400:dd09:1003:71:6820:57c2:c23b:44b7 • Performance & security by [Cloudflare](https://www.cloudflare.com/5xx-error-landing)

**Comment by elphen-wang** [comment]
> Traceback (most recent call last): File ".\request_llm\bridge_chatgpt.py", line 189, in predict if ('data: [DONE]' in chunk_decoded) or (len(json.loads(chunk_decoded[6:])['choices'][0]["delta"]) == 0): ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\json__init__.py", line 346, in loads return _default_decoder.decode(s) ^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 337, in decode obj, end = self.raw_decode(s, idx=_w(s, 0).end()) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 355, in raw_decode raise JSONDecodeError("Expecting value", s, err.value) from None json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> 
> 还有就是报错： Please enable cookies. Sorry, you have been blocked You are unable to access fakeopen.com Why have I been blocked? This website is using a security service to protect itself from online attacks. The action you just performed triggered the security solution. There are several actions that could trigger this block including submitting a certain word or phrase, a SQL command or malformed data.
> 
> What can I do to resolve this? You can email the site owner to let them know you were blocked. Please include what you were doing when this page came up and the Cloudflare Ray ID found at the bottom of this page.
> 
> Cloudflare Ray ID: 7fa088e2486adff5 • Your IP: Click to reveal 2400:dd09:1003:71:6820:57c2:c23b:44b7 • Performance & security by [Cloudflare](https://www.cloudflare.com/5xx-error-landing)

我这边一切正常，貌似没有问题。你排查一下是不是自己环境配置有问题。

**Comment by zangqiourun** [comment]
> > Traceback (most recent call last): File ".\request_llm\bridge_chatgpt.py", line 189, in predict if ('data: [DONE]' in chunk_decoded) or (len(json.loads(chunk_decoded[6:])['choices'][0]["delta"]) == 0): ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\json__init__.py", line 346, in loads return _default_decoder.decode(s) ^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 337, in decode obj, end = self.raw_decode(s, idx=_w(s, 0).end()) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 355, in raw_decode raise JSONDecodeError("Expecting value", s, err.value) from None json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> > 还有就是报错： Please enable cookies. Sorry, you have been blocked You are unable to access fakeopen.com Why have I been blocked? This website is using a security service to protect itself from online attacks. The action you just performed triggered the security solution. There are several actions that could trigger this block including submitting a certain word or phrase, a SQL command or malformed data.
> > What can I do to resolve this? You can email the site owner to let them know you were blocked. Please include what you were doing when this page came up and the Cloudflare Ray ID found at the bottom of this page.
> > Cloudflare Ray ID: 7fa088e2486adff5 • Your IP: Click to reveal 2400:dd09:1003:71:6820:57c2:c23b:44b7 • Performance & security by [Cloudflare](https://www.cloudflare.com/5xx-error-landing)
> 
> 我这边一切正常，貌似没有问题。你排查一下是不是自己环境配置有问题。

我的今天也好了 应该还是池子里某些token生命周期的问题

**Comment by zangqiourun** [comment]
> > Traceback (most recent call last): File ".\request_llm\bridge_chatgpt.py", line 189, in predict if ('data: [DONE]' in chunk_decoded) or (len(json.loads(chunk_decoded[6:])['choices'][0]["delta"]) == 0): ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\json__init__.py", line 346, in loads return _default_decoder.decode(s) ^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 337, in decode obj, end = self.raw_decode(s, idx=_w(s, 0).end()) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 355, in raw_decode raise JSONDecodeError("Expecting value", s, err.value) from None json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> > 还有就是报错： Please enable cookies. Sorry, you have been blocked You are unable to access fakeopen.com Why have I been blocked? This website is using a security service to protect itself from online attacks. The action you just performed triggered the security solution. There are several actions that could trigger this block including submitting a certain word or phrase, a SQL command or malformed data.
> > What can I do to resolve this? You can email the site owner to let them know you were blocked. Please include what you were doing when this page came up and the Cloudflare Ray ID found at the bottom of this page.
> > Cloudflare Ray ID: 7fa088e2486adff5 • Your IP: Click to reveal 2400:dd09:1003:71:6820:57c2:c23b:44b7 • Performance & security by [Cloudflare](https://www.cloudflare.com/5xx-error-landing)
> 
> 我这边一切正常，貌似没有问题。你排查一下是不是自己环境配置有问题。

你那边最近还正常么？ 我的最近一直都用不了
