### ISSUE TITLE
运行python main.py报错AttributeError: module 'config' has no attribute 'DEFAULT_FN_GROUPS'

### ISSUE THREAD

**Issue by WoCer2019** [elphen-wang/FreeAI#12]
你好：

替换完文件夹中的3个文件，并配置好API key，重新python -m pip install -r requirements.txt  最后运行python main.py报错，请问怎么解决？

错误：
Traceback (most recent call last):
  File "C:\Users\HUAWEI\gpt_academic\toolbox.py", line 713, in read_single_conf_with_lru_cache
    default_ref = getattr(importlib.import_module('config'), arg)   # 读取默认值作为数据类型转换的参考
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'config' has no attribute 'DEFAULT_FN_GROUPS'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HUAWEI\gpt_academic\toolbox.py", line 718, in read_single_conf_with_lru_cache
    r = getattr(importlib.import_module('config_private'), arg)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'config_private' has no attribute 'DEFAULT_FN_GROUPS'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HUAWEI\gpt_academic\main.py", line 264, in <module>
    main()
  File "C:\Users\HUAWEI\gpt_academic\main.py", line 37, in main
    DEFAULT_FN_GROUPS, = get_conf('DEFAULT_FN_GROUPS')
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HUAWEI\gpt_academic\toolbox.py", line 746, in get_conf
    r = read_single_conf_with_lru_cache(arg)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HUAWEI\gpt_academic\toolbox.py", line 721, in read_single_conf_with_lru_cache
    r = getattr(importlib.import_module('config'), arg)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'config' has no attribute 'DEFAULT_FN_GROUPS'

**Comment by irvingZ11** [comment]
同样问题，请问解决了吗
