### ISSUE TITLE
替换文件后,两个位置文件一样，且都只改了api_key，报错

### ISSUE THREAD

**Issue by LovebuildJ** [elphen-wang/FreeAI#7]
按照操作步骤docker部署的，启动之后访问 ip+端口，无法访问，然后有报错日志。
这是我的构建步骤：
`docker build -t gpt-academic .`
`docker run -d  -it -p 9002:9002 --restart=always gpt-academic` 

只改了两个文件的api_key和web_port。其他都没改。

```
                ^^^^^^^^^^^^^^^^^^^^^
  File "/gpt/crazy_functional.py", line 28, in get_crazy_functions
    from crazy_functions.批量Markdown翻译 import Markdown英译中
  File "/gpt/crazy_functions/批量Markdown翻译.py", line 2, in <module>
    from toolbox import update_ui, trimmed_format_exc, gen_time_str, disable_auto_promotion
ImportError: cannot import name 'disable_auto_promotion' from 'toolbox' (/gpt/toolbox.py)
 [PROXY] 网络代理状态：未配置。无代理状态下很可能无法访问OpenAI家族的模型。建议：检查USE_PROXY选项是否修改。 
None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
所有问询记录将自动保存在本地目录./gpt_log/chat_secrets.log, 请注意自我隐私保护哦！
Traceback (most recent call last):
  File "/gpt/main.py", line 238, in <module>
    main()
  File "/gpt/main.py", line 37, in main
    crazy_fns = get_crazy_functions()
                ^^^^^^^^^^^^^^^^^^^^^
  File "/gpt/crazy_functional.py", line 28, in get_crazy_functions
    from crazy_functions.批量Markdown翻译 import Markdown英译中
  File "/gpt/crazy_functions/批量Markdown翻译.py", line 2, in <module>
    from toolbox import update_ui, trimmed_format_exc, gen_time_str, disable_auto_promotion
ImportError: cannot import name 'disable_auto_promotion' from 'toolbox' (/gpt/toolbox.py)
```

**Comment by wingwwwc** [comment]
1.使用上一个版本的gpt_academic（貌似是昨晚刚刚更新了一次），新版本放进去会有toolbox的报错，老版本就只会api报错，因此我先用旧版本改改看。
2.在旧版本中使用pk-this-is-a-real-free-pool-token-for-everyone提示有法律风险不让用，尝试使用share_token的方法。
3."get_freeai_api.py"中Auth0()的参数名改变了，那句话应该替换成auth = Auth0(email_address=username, password=password).改完之后运行get_freeai_api任然报错, 无法正常获取share_token（应该是我装的OpenAIAuth的版本的问题？我直接pip装的）。
4.直接去Pandora 项目手动获取一下access token 然后通过访问https://ai.fakeopen.com/token 获取share_token粘贴到config和config_private 的 API_KEY =“xxxx”里面即可使用了。（不用把方法二注释打开）
